### ISSUE TITLE
HW 5 repo

### ISSUE THREAD

**Issue by wenhuizhang** [mapleknight/dist-sys-exercises-hw5#1]
https://github.com/gwDistSys15/

**Comment by mapleknight** [comment]
Hi Wenhui,
Do you mean that we need to fork this repo again?

**Comment by wenhuizhang** [comment]
Hi, this is a private repo, starts with hw5, you dont have to fork it unless several members need to work on it together :) 

hope i explained well..

May I close this request pls?

**Comment by mapleknight** [comment]
Sure, you can close it. 
I received the email for the private repo. Thanks so much!

**Comment by wenhuizhang** [comment]
my please, case closed
